//CommonJS, every file is module (by default)
//Module - encapsalated code (only share minimum)
const names = require('./4-names')

// console.log(names)
const sayHi = require('./5-utilis')
const data = require('./6-alternative-flavor')
require('./7-mind-grenade')
// console.log(data)
// sayHi('susan')
// sayHi(names.john)
// sayHi(names.peter)
